[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = ".cargo/x86_64-stellaros.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"